USE FIRMA
GO

ALTER TABLE ANGAJATI
ADD CONSTRAINT FK_ANGAJATI_FUNCTII FOREIGN KEY (IdFunctie)
REFERENCES FUNCTII(IdFunctie)

GO

ALTER TABLE ANGAJATI
ADD CONSTRAINT FK_ANGAJATI_DEPT FOREIGN KEY (IdDept)
REFERENCES DEPARTAMENTE(IdDept)

GO

ALTER TABLE VANZARI
ADD CONSTRAINT FK_VANZARI_PRODUS FOREIGN KEY (IdProdus)
REFERENCES PRODUSE(IdProdus)

GO

ALTER TABLE VANZARI
ADD CONSTRAINT FK_VANZARI_CLIENT FOREIGN KEY (IdClient)
REFERENCES CLIENTI(IdClient)

GO

ALTER TABLE VANZARI
ADD CONSTRAINT FK_VANZARI_ANGAJAT FOREIGN KEY (IdAngajat)
REFERENCES ANGAJATI(IdAngajat)

GO

ALTER TABLE PRODUSE
ADD CONSTRAINT FK_PRODUS_CATEGORIE FOREIGN KEY (IdCateg)
REFERENCES CATEGORII_PROD(IdCateg)

GO




